### ISSUE TITLE
User should be able to create a Customer account

### ISSUE THREAD

**Issue by stevebrownlee** [spooky-oysters/Bangazon-Command-Line-Application#1]
**Given** a new customer calls with a request for a representative to handle
**When** the user select the option to create a customer account
**Then** the user should be presented with prompts to enter in customer information

```bash
Enter customer name
>

Enter street address
>

Enter city
>

Enter state
>

Enter postal code
>

Enter phone number
>
```

**Comment by DreRandaci** [comment]
- Create class: `Customer.cs`
- Create class: `CustomerManager.cs`
- Method to `Add` a customer to the database
- Test that asserts if a customer exists in a collection and has the correct properties 
- - Customer can be added to a collection
- - Customers can be displayed in an ordered list
