### ISSUE TITLE
User should be able to select who the active Customer is

### ISSUE THREAD

**Issue by stevebrownlee** [spooky-oysters/Bangazon-Command-Line-Application#2]
**Given** the user needs to perform an action on behalf of a customer
**When** the user selects the option to choose which customer is active
**Then** the user should be presented with a numbered list of all customers
**And** be able to select one of the customers

```bash
Which customer will be active?
1. John Q. Public
2. Svetlana Z. Herevazena
>
```

**Comment by DreRandaci** [comment]
- A static, persistent `ActiveCustomer` method that is called in `Program.cs`
- Test that asserts if an `ActiveCustomer` currently exists. An ID is passed to the method and the customer with that ID is returned
- Test that asserts that given the option to change the active customer, the same variable is reassigned to new customer
- Pull ID based on position in customer collection
