### ISSUE TITLE
User should be able to add a product for a customer

### ISSUE THREAD

**Issue by stevebrownlee** [spooky-oysters/Bangazon-Command-Line-Application#4]
**Given** a customer has been made active in the program
**When** the user selects the option to add a product
**Then** the user should be prompted to enter in all appropriate information for a product
**And** when complete, the product should be added for the active customer

**Comment by DreRandaci** [comment]
- Requires an `ActiveCustomer` 
- Create file: `Product.cs`
- - `AddProduct` method in `Product.cs`
- Test that asserts if a product exists in a collection
- - Product can be added to a collection
- - Product has properties 
- - Products exist in the collection
